version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
